//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaDAL.BackEndDBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartonsJaunesHistory
    {
        public System.Guid carteJauneId { get; set; }
        public System.Guid joueurId { get; set; }
        public System.Guid matchId { get; set; }
        public bool isActive { get; set; }
        public int minuteRecue { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public System.Guid equipeId { get; set; }
    
        public virtual CartonsJaunesHistory CartonsJaunesHistory1 { get; set; }
        public virtual CartonsJaunesHistory CartonsJaunesHistory2 { get; set; }
        public virtual Equipes Equipes { get; set; }
        public virtual Joueurs Joueurs { get; set; }
        public virtual Matchs Matchs { get; set; }
    }
}
