//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaDAL.BackEndDBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championnats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Championnats()
        {
            this.EquipesParticipationHistory = new HashSet<EquipesParticipationHistory>();
            this.Intersaisons = new HashSet<Intersaisons>();
            this.Quarters = new HashSet<Quarters>();
        }
    
        public System.Guid championnatId { get; set; }
        public int annee { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipesParticipationHistory> EquipesParticipationHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intersaisons> Intersaisons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quarters> Quarters { get; set; }
    }
}
