//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaDAL.BackEndDBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeuillesDeMatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeuillesDeMatch()
        {
            this.JoueursParticipationHistory = new HashSet<JoueursParticipationHistory>();
        }
    
        public System.Guid feuilleId { get; set; }
        public System.Guid matchId { get; set; }
        public System.Guid equipeId { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        public virtual Equipes Equipes { get; set; }
        public virtual Matchs Matchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoueursParticipationHistory> JoueursParticipationHistory { get; set; }
    }
}
