//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaDAL.BackEndDBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoueursParticipationHistory
    {
        public System.Guid joueurId { get; set; }
        public System.Guid feuilleId { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        public virtual FeuillesDeMatch FeuillesDeMatch { get; set; }
        public virtual Joueurs Joueurs { get; set; }
    }
}
