//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaDAL.BackEndDBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matchs()
        {
            this.CartonsJaunesHistory = new HashSet<CartonsJaunesHistory>();
            this.CartonsRougesHistory = new HashSet<CartonsRougesHistory>();
            this.FeuillesDeMatch = new HashSet<FeuillesDeMatch>();
            this.GoalsHistory = new HashSet<GoalsHistory>();
        }
    
        public System.Guid matchId { get; set; }
        public System.DateTime matchDate { get; set; }
        public System.Guid equipe1Id { get; set; }
        public System.Guid equipe2Id { get; set; }
        public int equipe1Points { get; set; }
        public int equipe2Points { get; set; }
        public bool isPlayed { get; set; }
        public System.DateTime lastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartonsJaunesHistory> CartonsJaunesHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartonsRougesHistory> CartonsRougesHistory { get; set; }
        public virtual Equipes Equipes { get; set; }
        public virtual Equipes Equipes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeuillesDeMatch> FeuillesDeMatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalsHistory> GoalsHistory { get; set; }
    }
}
